/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-base': '#0F0F0F',
        'surface-card': '#181818',
        'surface-interactive': '#252525',
        'surface-dim': '#131313',
        'surface': '#131313',
        'surface-container': '#201f1f',
        'surface-container-low': '#1c1b1b',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-container-lowest': '#0e0e0e',
        'surface-bright': '#3a3939',
        'border-subtle': '#2A2A2A',
        'outline-variant': '#44474c',
        'outline': '#8e9197',
        'primary': '#d5e5fe',
        'primary-container': '#b9c9e1',
        'primary-fixed': '#d4e4fc',
        'on-primary': '#223144',
        'accent-blue': '#B9C9E1',
        'accent-pink': '#E3B6D8',
        'text-primary': '#FFFFFF',
        'text-secondary': '#8C8C8C',
        'status-live': '#4ADE80',
        'status-warning': '#F59E0B',
        'status-danger': '#EF4444',
        'tertiary': '#71ff9e',
        'tertiary-container': '#4fe283',
        'secondary': '#e6b9db',
        'secondary-container': '#603e5a',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#c4c6cd',
        'background': '#131313',
        'on-background': '#e5e2e1',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'gutter-xs': '4px',
        'gutter-sm': '8px',
        'gutter-md': '16px',
        'gutter-lg': '24px',
        'gutter-xl': '32px',
        'page-padding-mobile': '16px',
        'card-padding': '32px',
        'card-padding-mobile': '20px',
        'page-padding': '40px',
        'canvas-dot': '40px',
        'max-width': '1200px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'display-hero': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'kpi-value': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'mono-tag': ['JetBrains Mono', 'monospace'],
        'mono-data': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-hero': ['84px', { lineHeight: '76px', letterSpacing: '-0.05em', fontWeight: '800' }],
        'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'kpi-value': ['64px', { lineHeight: '68px', letterSpacing: '-0.04em', fontWeight: '600' }],
        'display-hero-mobile': ['48px', { lineHeight: '52px', letterSpacing: '-0.04em', fontWeight: '800' }],
        'body-sm': ['12px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '400' }],
        'kpi-value-mobile': ['40px', { lineHeight: '44px', letterSpacing: '-0.03em', fontWeight: '600' }],
        'headline-lg': ['42px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'mono-tag': ['11px', { lineHeight: '14px', letterSpacing: '0em', fontWeight: '500' }],
        'mono-data': ['13px', { lineHeight: '18px', letterSpacing: '-0.01em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
